apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: abinashdash891/petclinic:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata: 
  name: perclinic-ssvc
spec:
  selector:
    app: petclinic
  ports: 
    - protocol: "TCP"
      port: 80 
      targetPort: 8080
  type: LoadBalancer  
